add wave -radix hex sim:/top/*
add wave -radix hex sim:/top/lc3_if/*
add wave -radix hex sim:/top/LC3/DATAPATH/PC
add wave -radix hex sim:/top/LC3/DATAPATH/IR
add wave -radix hex sim:/top/LC3/DATAPATH/MAR
add wave -radix hex sim:/top/LC3/DATAPATH/MDR
add wave -radix hex sim:/top/LC3/DATAPATH/selMDR
add wave -radix hex sim:/top/LC3/DATAPATH/memWEi
add wave -radix hex sim:/top/LC3/DATAPATH/PSR
add wave -radix hex sim:/top/LC3/DATAPATH/SavedUSP
add wave -radix hex sim:/top/LC3/DATAPATH/SavedSSP
add wave -radix hex sim:/top/LC3/DATAPATH/NZP 
add wave -radix hex sim:/top/LC3/DATAPATH/INTP_reg
add wave -radix hex sim:/top/LC3/DATAPATH/REGFILE
add wave -radix hex sim:/top/LC3/CONTROL/CurrentState