add wave -radix hex sim:/top/*
add wave -radix hex sim:/top/lc3_if/*
add wave -radix hex sim:/top/LC3/DATAPATH/PC
add wave -radix hex sim:/top/LC3/DATAPATH/IR
add wave -radix hex sim:/top/LC3/DATAPATH/MAR
add wave -radix hex sim:/top/LC3/DATAPATH/MDR
add wave -radix hex sim:/top/LC3/DATAPATH/selMDR
add wave -radix hex sim:/top/LC3/DATAPATH/memWEi
add wave -radix hex sim:/top/LC3/DATAPATH/PSR
add wave -radix hex sim:/top/LC3/DATAPATH/ldCC
add wave -radix hex sim:/top/LC3/DATAPATH/SavedUSP
add wave -radix hex sim:/top/LC3/DATAPATH/SavedSSP
add wave -radix hex sim:/top/LC3/DATAPATH/NZP 
add wave -radix hex sim:/top/LC3/DATAPATH/INTP_reg
add wave -radix hex sim:/top/LC3/DATAPATH/REGFILE
add wave -radix hex sim:/top/LC3/DATAPATH/VectorMUX
add wave -radix hex sim:/top/LC3/DATAPATH/Vector
add wave -radix hex sim:/top/LC3/DATAPATH/ldVector
add wave -radix hex sim:/top/LC3/DATAPATH/INTV
add wave -radix hex sim:/top/LC3/DATAPATH/BUSS
add wave -radix hex sim:/top/LC3/CONTROL/state
add wave -radix hex sim:/top/LC3/CONTROL/NextState
add wave -radix hex sim:/top/LC3/CONTROL/INT
add wave -radix hex sim:/top/LC3/CONTROL/ldMAR
add wave -radix hex sim:/top/LC3/CONTROL/branch_enable
add wave -radix hex sim:/top/LC3/CONTROL/DR
add wave -radix hex sim:/top/LC3/CONTROL/regWE
add wave -radix hex sim:/EnvironmentPkg::opcode_c
